// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCalculatedColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCalculatedColumn'](arg1, arg2, arg3);
}

export function AddCalculatedColumnByID(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCalculatedColumnByID'](arg1, arg2, arg3);
}

export function AddColumn(arg1, arg2) {
  return window['go']['main']['App']['AddColumn'](arg1, arg2);
}

export function AddColumnByID(arg1, arg2) {
  return window['go']['main']['App']['AddColumnByID'](arg1, arg2);
}

export function AddRow(arg1) {
  return window['go']['main']['App']['AddRow'](arg1);
}

export function AddRowByID(arg1) {
  return window['go']['main']['App']['AddRowByID'](arg1);
}

export function CreateEmptyTable(arg1) {
  return window['go']['main']['App']['CreateEmptyTable'](arg1);
}

export function CreateEmptyTableByID(arg1, arg2) {
  return window['go']['main']['App']['CreateEmptyTableByID'](arg1, arg2);
}

export function GetParamValue(arg1) {
  return window['go']['main']['App']['GetParamValue'](arg1);
}

export function GetTableCount() {
  return window['go']['main']['App']['GetTableCount']();
}

export function GetTableData(arg1) {
  return window['go']['main']['App']['GetTableData'](arg1);
}

export function GetTableDataByID(arg1) {
  return window['go']['main']['App']['GetTableDataByID'](arg1);
}

export function GetTableInfo(arg1) {
  return window['go']['main']['App']['GetTableInfo'](arg1);
}

export function GetTableNames() {
  return window['go']['main']['App']['GetTableNames']();
}

export function LoadTable(arg1, arg2) {
  return window['go']['main']['App']['LoadTable'](arg1, arg2);
}

export function LoadTableByID(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadTableByID'](arg1, arg2, arg3);
}

export function RemoveTable(arg1) {
  return window['go']['main']['App']['RemoveTable'](arg1);
}

export function RemoveTableByID(arg1) {
  return window['go']['main']['App']['RemoveTableByID'](arg1);
}

export function SaveTable(arg1, arg2) {
  return window['go']['main']['App']['SaveTable'](arg1, arg2);
}

export function SaveTableByID(arg1, arg2) {
  return window['go']['main']['App']['SaveTableByID'](arg1, arg2);
}

export function UpdateCellValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCellValue'](arg1, arg2, arg3, arg4);
}

export function UpdateCellValueByID(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCellValueByID'](arg1, arg2, arg3, arg4);
}

export function UpdateColumnName(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateColumnName'](arg1, arg2, arg3);
}

export function UpdateColumnNameByID(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateColumnNameByID'](arg1, arg2, arg3);
}
